version: "3.7"
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: broker
        container_name: broker-application
        restart: always
        working_dir: /var/www/app/
        volumes:
            - ./:/var/www
        networks:
            - broker-network
        ports:
            - '5173:5173'
        env_file:
            - ./app/.env

    nginx:
        image: nginx:alpine
        container_name: broker-nginx
        restart: always
        ports:
            - "${NGINX_PORT:-8080}:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - broker-network
        env_file:
            - ./app/.env

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - ${RABBITMQ_AMQP_PORT:-5672}:5672
            - ${RABBITMQ_HTTP_PORT:-15672}:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-root}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-pass}
        volumes:
            - ./docker/data/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker/data/rabbitmq/log/:/var/log/rabbitmq
        command: ["bash", "-c", "chmod 600 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
        networks:
            - broker-network
networks:
    broker-network:
        driver: bridge